#!/usr/bin/env node
/* Offline .glb -> three.js JSON converter for the capybara.
 *
 * GLTFLoader is not in vendor/three.min.js and the add-on loaders ship as ES
 * modules only, so a .glb cannot be loaded at runtime without a build step.
 * ObjectLoader IS in the bundle, so the model is converted here, offline, and
 * committed as a plain script that assigns a global. Nothing new is required
 * at runtime, and there is no async load at boot.
 *
 *   npm i three@0.160.0            # dev only, not committed; match vendor/
 *   node tools/glb2json.mjs assets/capybara.glb js/capymodel.js
 *
 * What it fixes up along the way, none of which the source .glb carries:
 *   - welds the split vertices and averages normals (the export is flat-shaded:
 *     ~3 verts per triangle), which is what gives the smooth figurine surface
 *   - generates cylindrical UVs, since the mesh has no TEXCOORD_0 at all
 *   - bakes vertex colours from the SKIN WEIGHTS: whichever bone owns a vertex
 *     decides its colour, so the feet come out dark without any hand painting
 *   - bakes the scale down to game units, so nothing carries a non-unit scale
 *     at runtime (stack.js reparents by world position/quaternion and would
 *     otherwise resize the debris)
 *   - drops the animation (scene.toJSON() omits clips anyway)
 */
import fs from 'fs';
import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';

const [,, IN = 'assets/capybara.glb', OUT = 'js/capymodel.js'] = process.argv;

/* Bones the runtime adapter drives by name. Renaming any of these in Blender
   breaks the rig contract — capyrig.js refuses the model and the procedural
   capybara stays up, rather than rendering a broken animal. */
const REQUIRED = ['head0', 'neck1',
  'leg_front_left_top0', 'leg_front_right_top0',
  'leg_hind_left_top0',  'leg_hind_right_top0'];

const TARGET_HEIGHT = 1.50;        // game units, matched to the procedural build

// sRGB source colours; THREE.Color converts them to the linear working space,
// which is what a vertex-colour attribute is sampled as
const C_BODY = new THREE.Color(0xbe8a63);   // mat.fur
const C_LEG  = new THREE.Color(0x8a5a40);   // mat.furDark
const C_FOOT = new THREE.Color(0x2b1d15);   // near-black hooves/toes

const buf = fs.readFileSync(IN);
const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);

new GLTFLoader().parse(ab, '', (gltf) => {
  const root = gltf.scene;
  let sk = null;
  root.traverse(o => { if (o.isSkinnedMesh) sk = o; });
  if (!sk) die('no SkinnedMesh in ' + IN);

  const missing = REQUIRED.filter(n => !sk.skeleton.bones.some(b => b.name === n));
  if (missing.length) die('missing required bone(s): ' + missing.join(', '));

  const src = sk.geometry;
  const geo = weld(src);
  sk.geometry = geo;

  /* --- collapse the armature's export rotation --------------------------
     The exporter leaves a Z-up -> Y-up rotation on the armature node. Per the
     glTF spec a skinned mesh ignores its own node transform, and three honours
     that (bindMode 'attached' recomputes bindMatrixInverse from matrixWorld),
     so the mesh renders in the bone hierarchy's space while that rotation sits
     on the node doing nothing to it. Leave it in place and every measurement
     taken through matrixWorld is in a space the mesh does not actually render
     in. Pushing it down into the bone chain leaves the bones' world transforms
     untouched and makes node space, geometry space and bone space the same
     thing — after this, one coordinate system for the whole file. */
  const rigNode = sk.parent;
  const boneRoot = rigNode.children.find(c => c.isBone);
  if (!boneRoot) die('armature node has no root bone');
  boneRoot.applyMatrix4(rigNode.matrix);
  rigNode.position.set(0, 0, 0);
  rigNode.quaternion.identity();
  rigNode.scale.set(1, 1, 1);
  rigNode.updateMatrixWorld(true);

  /* --- scale to game units, then drop the feet onto y = 0 ---------------
     Baked into the geometry and the bone translations, so the emitted model
     carries no scale or offset node and needs no compensation at runtime. */
  const S = TARGET_HEIGHT / bboxOf(sk).getSize(new THREE.Vector3()).y;
  scaleAttr(geo.attributes.position, S);
  root.traverse(o => { if (o.isBone) o.position.multiplyScalar(S); });
  root.updateMatrixWorld(true);

  const drop = bboxOf(sk).min.y;
  offsetAttrY(geo.attributes.position, -drop);
  boneRoot.position.y -= drop;
  root.updateMatrixWorld(true);

  paint(sk);

  // bind pose is whatever the bones are in right now
  sk.skeleton.calculateInverses();

  geo.computeBoundingBox();
  geo.computeBoundingSphere();

  const fin = bboxOf(sk);
  const size = fin.getSize(new THREE.Vector3());

  round(geo);
  const json = root.toJSON();
  const body =
    '/* GENERATED by tools/glb2json.mjs from ' + IN + ' — do not hand-edit.\n' +
    '   Re-run the converter instead; see CLAUDE.md. */\n' +
    'const CAPY_MODEL = ' + JSON.stringify(json) + ';\n';
  fs.writeFileSync(OUT, body);

  const kb = n => (n / 1024).toFixed(0) + ' KB';
  console.log('capybara ->', OUT);
  console.log('  verts   ', src.attributes.position.count, '->', geo.attributes.position.count,
              '(welded)   tris', geo.index.count / 3);
  console.log('  bones   ', sk.skeleton.bones.length);
  console.log('  scale   ', S.toFixed(5), ' size',
              size.toArray().map(n => n.toFixed(2)).join(' x '),
              ' feet at y =', fin.min.y.toFixed(3));
  console.log('  size    ', kb(fs.statSync(OUT).size), 'raw');
}, e => die(e && e.message ? e.message : String(e)));

function die(msg){ console.error('glb2json: ' + msg); process.exit(1); }

/* Bind-pose bounds, measured straight off the position attribute.
   Box3.setFromObject caches its result on the SkinnedMesh, so it keeps handing
   back pre-scale numbers once anything here has rescaled the geometry. No
   matrixWorld: once the armature rotation is collapsed the geometry is already
   in the space the mesh renders in. */
function bboxOf(sk){
  const pos = sk.geometry.attributes.position;
  const v = new THREE.Vector3(), box = new THREE.Box3();
  for (let i = 0; i < pos.count; i++) box.expandByPoint(v.fromBufferAttribute(pos, i));
  return box;
}

/* -------------------------------------------------------------------------
   Weld vertices by position and average their normals.
   The Blender export splits every vertex per face, which renders flat-shaded
   and reads as low-poly. Merging by position and summing normals restores the
   one-continuous-surface look, and drops the vertex count ~5.6x.
   ------------------------------------------------------------------------- */
function weld(g){
  const pos = g.attributes.position, nor = g.attributes.normal;
  const si = g.attributes.skinIndex, sw = g.attributes.skinWeight;
  const idx = g.index;
  const map = new Map(), remap = new Int32Array(pos.count);
  const P = [], N = [], SI = [], SW = [];
  const q = v => Math.round(v * 1e4);

  for (let i = 0; i < pos.count; i++){
    const key = q(pos.getX(i)) + '_' + q(pos.getY(i)) + '_' + q(pos.getZ(i));
    let j = map.get(key);
    if (j === undefined){
      j = P.length / 3;
      map.set(key, j);
      P.push(pos.getX(i), pos.getY(i), pos.getZ(i));
      N.push(0, 0, 0);
      SI.push(si.getX(i), si.getY(i), si.getZ(i), si.getW(i));
      SW.push(sw.getX(i), sw.getY(i), sw.getZ(i), sw.getW(i));
    }
    remap[i] = j;
    N[j*3] += nor.getX(i); N[j*3+1] += nor.getY(i); N[j*3+2] += nor.getZ(i);
  }
  for (let j = 0; j < N.length / 3; j++){
    const l = Math.hypot(N[j*3], N[j*3+1], N[j*3+2]) || 1;
    N[j*3] /= l; N[j*3+1] /= l; N[j*3+2] /= l;
  }
  const NI = new Uint32Array(idx.count);
  for (let i = 0; i < idx.count; i++) NI[i] = remap[idx.getX(i)];

  const out = new THREE.BufferGeometry();
  out.setAttribute('position', new THREE.Float32BufferAttribute(P, 3));
  out.setAttribute('normal',   new THREE.Float32BufferAttribute(N, 3));
  out.setAttribute('skinIndex',  new THREE.Uint16BufferAttribute(SI, 4));
  out.setAttribute('skinWeight', new THREE.Float32BufferAttribute(SW, 4));
  out.setIndex(new THREE.BufferAttribute(NI, 1));
  return out;
}

function scaleAttr(a, s){
  for (let i = 0; i < a.count; i++) a.setXYZ(i, a.getX(i)*s, a.getY(i)*s, a.getZ(i)*s);
  a.needsUpdate = true;
}

function offsetAttrY(a, dy){
  for (let i = 0; i < a.count; i++) a.setY(i, a.getY(i) + dy);
  a.needsUpdate = true;
}

/* -------------------------------------------------------------------------
   Generate UVs and bake vertex colours.

   UVs: a cylindrical projection about the body's long axis, seam tucked onto
   the belly midline. It is not a real unwrap and it stretches over the legs,
   but it only ever carries the runtime fur-noise texture, and high-frequency
   noise hides both the seam and the stretch. Anything structured would not
   survive this projection.

   Colours: the foot mask is taken from HEIGHT, not from the skin weights.
   Weights look like the principled choice and are not: this rig's ankle/toe
   bones are wildly asymmetric front to back — the hind ankle sits at y = 0.168
   but the front ankle at y = 0.018 — so weighting by them paints a boot half
   way up the hind shins while catching only 5-9 vertices on each front foot,
   which is invisible. Every foot is planted at y = 0 in the bind pose (the
   converter grounds the model), so a height ramp gives all four the same sock.
   Bone weights are still used, but only to answer "is this vertex on a leg at
   all", so nothing on the body can darken.
   ------------------------------------------------------------------------- */
const SOCK_TOP  = 0.115;   // fully body-coloured at and above this height
const SOCK_FULL = 0.045;   // fully dark at and below it

function paint(sk){
  const geo = sk.geometry;
  const pos = geo.attributes.position;
  const si = geo.attributes.skinIndex, sw = geo.attributes.skinWeight;
  const names = sk.skeleton.bones.map(b => b.name);

  const onLeg = names.map(n => /^leg_/.test(n) ? 1 : 0);

  const p = new THREE.Vector3();
  const box = bboxOf(sk);
  const zMin = box.min.z, zSpan = Math.max(1e-6, box.max.z - box.min.z);
  const midY = (box.min.y + box.max.y) * 0.5;

  const uv = new Float32Array(pos.count * 2);
  const col = new Float32Array(pos.count * 3);
  const c = new THREE.Color();

  for (let i = 0; i < pos.count; i++){
    p.fromBufferAttribute(pos, i);

    // seam falls where atan2 wraps, i.e. straight down the belly
    uv[i*2]     = Math.atan2(p.x, p.y - midY) / (Math.PI * 2) + 0.5;
    uv[i*2 + 1] = (p.z - zMin) / zSpan;

    let leg = 0;
    for (const k of ['X', 'Y', 'Z', 'W']){
      leg += onLeg[si['get' + k](i)] * sw['get' + k](i);
    }
    let d = leg < 0.25 ? 0
          : THREE.MathUtils.clamp((SOCK_TOP - p.y) / (SOCK_TOP - SOCK_FULL), 0, 1);
    d = d * d * (3 - 2 * d);                       // smoothstep, softer ankle line

    // body -> leg -> foot, so the darkening ramps instead of banding
    if (d < 0.5) c.copy(C_BODY).lerp(C_LEG, d / 0.5);
    else         c.copy(C_LEG).lerp(C_FOOT, (d - 0.5) / 0.5);
    col[i*3] = c.r; col[i*3+1] = c.g; col[i*3+2] = c.b;
  }
  geo.setAttribute('uv', new THREE.BufferAttribute(uv, 2));
  geo.setAttribute('color', new THREE.BufferAttribute(col, 3));
}

// trim the serialized precision — this is most of the file size
function round(geo){
  const fix = (name, dp) => {
    const a = geo.attributes[name];
    if (!a) return;
    const m = Math.pow(10, dp);
    for (let i = 0; i < a.array.length; i++) a.array[i] = Math.round(a.array[i] * m) / m;
  };
  fix('position', 4);
  fix('normal', 3);
  fix('uv', 4);
  fix('color', 3);
  fix('skinWeight', 3);
}
